In [46]:
import numpy as np
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

In [47]:
# pandas series with date
date_s = pd.Series(pd.date_range("1/1/2015", periods=5))
date_s

0   2015-01-01
1   2015-01-02
2   2015-01-03
3   2015-01-04
4   2015-01-05
dtype: datetime64[ns]

In [48]:
# dataframe indexing and slicing with loc and iloc
df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]}, index=["a", "b", "c"])
df
df.iloc[0:2, :]
df.loc[['a', 'b'], :]

foo  bar
a    1    4
b    2    5
c    3    6

foo  bar
a    1    4
b    2    5

foo  bar
a    1    4
b    2    5

In [49]:
df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})
df
subset = df["foo"]
# subset is a view of dataframe
subset.iloc[0] = 100

df

foo  bar
0    1    4
1    2    5
2    3    6

foo  bar
0  100    4
1    2    5
2    3    6

In [50]:
df = pd.DataFrame(
    {"A": [3, 5, 7], "B": ["a", "b", "c"], "C": [1.2, 3.4, None]}, index=[2, 3, 9]
)
df

A  B    C
2  3  a  1.2
3  5  b  3.4
9  7  c  NaN

In [51]:
type(df.index)

pandas.core.indexes.base.Index

In [52]:
df.iloc[1, 0]

5

In [53]:
# condition in loc and where yield different results
df.loc[df["A"] > 3]

# where returns a dataframe with NaN
df.where(df["A"] > 3)

A  B    C
3  5  b  3.4
9  7  c  NaN

A    B    C
2  NaN  NaN  NaN
3  5.0    b  3.4
9  7.0    c  NaN

In [54]:
df = pd.DataFrame({"col1": list("ABBC"), "col2": list("ZZXY")})
df

# three conditions, on for each choice
conditions = [
    (df["col2"] == "Z") & (df["col1"] == "A"),
    (df["col2"] == "Z") & (df["col1"] == "B"),
    (df["col1"] == "B"),
]

choices = ["yellow", "blue", "purple"]

df["color"] = np.select(conditions, choices, default="black")

df

col1 col2
0    A    Z
1    B    Z
2    B    X
3    C    Y

col1 col2   color
0    A    Z  yellow
1    B    Z    blue
2    B    X  purple
3    C    Y   black

In [55]:
# pseudo random number generator
np.random.seed(1000)
np.random.randint(10, size=15)
np.random.seed(1000)
np.random.randint(10, size=15)

array([3, 7, 7, 0, 1, 0, 9, 8, 9, 4, 9, 4, 4, 2, 9])

array([3, 7, 7, 0, 1, 0, 9, 8, 9, 4, 9, 4, 4, 2, 9])

In [56]:
n = 10
np.random.seed(1000)
df = pd.DataFrame(np.random.randint(n / 2, size=(n, 2)), columns=list("bc"))

df.index.name = "a"
df
# use string conditions to filter rows
df.query("a < b & b < c")

b  c
a      
0  3  0
1  3  4
2  1  0
3  1  0
4  1  4
5  3  4
6  4  2
7  2  1
8  4  4
9  2  1

b  c
a      
1  3  4

In [57]:
df = pd.DataFrame(
    {"col": ["A", "A", "B", "B"], "A": [80, 23, np.nan, 22], "B": [80, 55, 76, 67]}
)
df

# select row key = col key values
idx, cols = pd.factorize(df["col"])
idx
cols

col     A   B
0   A  80.0  80
1   A  23.0  55
2   B   NaN  76
3   B  22.0  67

array([0, 0, 1, 1])

Index(['A', 'B'], dtype='object')

In [58]:
# reindex dataframe with certain values
df.reindex(cols, axis=1).to_numpy()[np.arange(len(df)), idx]

array([80., 23., 76., 67.])

In [59]:
arrs = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"],
]

tups = list(zip(*arrs))
tups
l1, l2 = zip(*tups)
l1
l2

[('bar', 'one'),
 ('bar', 'two'),
 ('baz', 'one'),
 ('baz', 'two'),
 ('foo', 'one'),
 ('foo', 'two'),
 ('qux', 'one'),
 ('qux', 'two')]

('bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux')

('one', 'two', 'one', 'two', 'one', 'two', 'one', 'two')

In [60]:
index = pd.MultiIndex.from_tuples(tups, names=["first", "second"])
index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [61]:
s = pd.Series(np.random.randn(8), index=index)
s

first  second
bar    one      -0.182377
       two       0.103193
baz    one      -0.138422
       two       0.705692
foo    one       1.271795
       two      -0.986747
qux    one      -0.334835
       two      -0.099482
dtype: float64

In [62]:
s = pd.Series(np.random.randn(8), index=index)
s

first  second
bar    one       0.407192
       two       0.919388
baz    one       0.312118
       two       1.533161
foo    one      -0.550174
       two      -0.383147
qux    one      -0.822941
       two       1.600083
dtype: float64

In [63]:
# get index values at a certain level
s.index.get_level_values(1)

Index(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two'], dtype='object', name='second')

In [64]:
df = pd.DataFrame(np.random.randn(3, 8), index=["A", "B", "C"], columns=index)
df.index.name = 'rows'
df
df.columns.levels
type(df.columns)
df.columns.get_level_values(0)

first        bar                 baz                 foo                 qux   
second       one       two       one       two       one       two       one   
rows                                                                           
A      -0.069281  0.083209 -0.326925 -0.045797 -0.304460  1.923010 -0.078659  \
B      -1.617982  0.867261 -1.040437  0.650421  2.699646  0.802025 -1.096921   
C      -0.422870 -0.330401 -1.111163 -0.742006  2.574759  1.073213 -1.866135   

first             
second       two  
rows              
A      -0.582066  
B      -0.178054  
C      -0.647177

FrozenList([['bar', 'baz', 'foo', 'qux'], ['one', 'two']])

pandas.core.indexes.multi.MultiIndex

Index(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'], dtype='object', name='first')

In [65]:
df = pd.DataFrame(np.random.randn(6, 6), index=index[:6], columns=index[:6])
df

first              bar                 baz                 foo          
second             one       two       one       two       one       two
first second                                                            
bar   one     1.082241  0.176670 -0.835328 -1.694998  1.133417  1.048531
      two    -2.128325 -1.437139  0.177937  1.394423  0.291320 -0.082006
baz   one     0.644243  0.328080  0.857433 -0.936969  0.180075 -1.423371
      two    -0.367756 -1.523288 -0.634772  0.987404 -1.016020  2.045724
foo   one     0.249999  0.651163 -1.266024  1.374156 -0.609905  0.030758
      two     0.819657  1.454314 -0.583676  0.415347  0.667026  0.869495

In [66]:
idx = pd.IndexSlice
df.loc[idx[:, "one"], idx[:, "one"]]

first              bar       baz       foo
second             one       one       one
first second                              
bar   one     1.082241 -0.835328  1.133417
baz   one     0.644243  0.857433  0.180075
foo   one     0.249999 -1.266024 -0.609905

In [67]:
df.loc[(slice(None), "one"), (slice(None), "one")]

first              bar       baz       foo
second             one       one       one
first second                              
bar   one     1.082241 -0.835328  1.133417
baz   one     0.644243  0.857433  0.180075
foo   one     0.249999 -1.266024 -0.609905

In [68]:
# select values at a certain level with certain key in this level
dfs = df.xs("one", level='second', axis=1, drop_level=False)
dfs
dfs.shape
reset_dfs = dfs.reset_index(level=1, col_level=1)
reset_dfs
reset_dfs.shape
reset_dfs.columns

first              bar       baz       foo
second             one       one       one
first second                              
bar   one     1.082241 -0.835328  1.133417
      two    -2.128325  0.177937  0.291320
baz   one     0.644243  0.857433  0.180075
      two    -0.367756 -0.634772 -1.016020
foo   one     0.249999 -1.266024 -0.609905
      two     0.819657 -0.583676  0.667026

(6, 3)

first               bar       baz       foo
second second       one       one       one
first                                      
bar       one  1.082241 -0.835328  1.133417
bar       two -2.128325  0.177937  0.291320
baz       one  0.644243  0.857433  0.180075
baz       two -0.367756 -0.634772 -1.016020
foo       one  0.249999 -1.266024 -0.609905
foo       two  0.819657 -0.583676  0.667026

(6, 4)

MultiIndex([(   '', 'second'),
            ('bar',    'one'),
            ('baz',    'one'),
            ('foo',    'one')],
           names=['first', 'second'])

In [69]:
df.xs("one", level="second", axis=1, drop_level=True)

first              bar       baz       foo
first second                              
bar   one     1.082241 -0.835328  1.133417
      two    -2.128325  0.177937  0.291320
baz   one     0.644243  0.857433  0.180075
      two    -0.367756 -0.634772 -1.016020
foo   one     0.249999 -1.266024 -0.609905
      two     0.819657 -0.583676  0.667026

In [70]:
df = pd.DataFrame(np.random.randn(3, 8), index=["A", "B", "C"], columns=index)
df

first        bar                 baz                 foo                 qux   
second       one       two       one       two       one       two       one   
A      -1.202703  2.861769 -2.681592 -1.168812 -0.584164  0.818250  1.590437  \
B       0.447029  1.938420 -0.390319 -0.580696  1.948987 -1.862551 -0.568357   
C       0.895364 -0.236262  0.441098 -0.992414  0.295505  0.042160  0.762139   

first             
second       two  
A      -0.258288  
B       0.979224  
C       0.627956

In [71]:
# select value with conditions on two levels of index
df["bar", "one"]

A   -1.202703
B    0.447029
C    0.895364
Name: (bar, one), dtype: float64

In [72]:
df[["foo", "qux"]].columns.levels

FrozenList([['bar', 'baz', 'foo', 'qux'], ['one', 'two']])

In [73]:
# reindex series, if the new index is not in the original index, NaN is filled
s
s.reindex(
    [("foo", "two"), ("bar", "one"), ("qux", "one"), ("baz", "one"), ("new", "new")]
)

first  second
bar    one       0.407192
       two       0.919388
baz    one       0.312118
       two       1.533161
foo    one      -0.550174
       two      -0.383147
qux    one      -0.822941
       two       1.600083
dtype: float64

first  second
foo    two      -0.383147
bar    one       0.407192
qux    one      -0.822941
baz    one       0.312118
new    new            NaN
dtype: float64

In [74]:
from pandas import CategoricalDtype

df = pd.DataFrame({"A": np.arange(6), "B": list("aabbca")})

df["B"] = df["B"].astype(CategoricalDtype(list("cab")))

df
df.info()

A  B
0  0  a
1  1  a
2  2  b
3  3  b
4  4  c
5  5  a

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   A       6 non-null      int64   
 1   B       6 non-null      category
dtypes: category(1), int64(1)
memory usage: 318.0 bytes


In [75]:
# set index with a column
df2 = df.set_index("B", drop=False)
df2
df2.index.name = "b"
df2.loc["a"]

A  B
B      
a  0  a
a  1  a
b  2  b
b  3  b
c  4  c
a  5  a

A  B
b      
a  0  a
a  1  a
a  5  a

In [76]:
df = pd.DataFrame(
    [
        [np.nan, 2, np.nan, 0],
        [3, 4, np.nan, 1],
        [np.nan, np.nan, np.nan, np.nan],
        [np.nan, 3, np.nan, 4],
    ],
    columns=list("ABCD"),
)
df

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [77]:
dfc = df.fillna(df.mean())
dfc

A    B   C         D
0  3.0  2.0 NaN  0.000000
1  3.0  4.0 NaN  1.000000
2  3.0  3.0 NaN  1.666667
3  3.0  3.0 NaN  4.000000

In [78]:
dff = df.fillna(method='ffill').fillna(method='bfill').dropna(axis=1)
dff

A    B    D
0  3.0  2.0  0.0
1  3.0  4.0  1.0
2  3.0  4.0  1.0
3  3.0  3.0  4.0

In [79]:
dfc.loc[:, "C"] = dfc.apply(lambda x: x["A"] + 1, axis=1)
dfc

A    B    C         D
0  3.0  2.0  4.0  0.000000
1  3.0  4.0  4.0  1.000000
2  3.0  3.0  4.0  1.666667
3  3.0  3.0  4.0  4.000000

In [80]:
dfr = df.fillna(method="backfill", axis=1)
dfr

A    B    C    D
0  2.0  2.0  0.0  0.0
1  3.0  4.0  1.0  1.0
2  NaN  NaN  NaN  NaN
3  3.0  3.0  4.0  4.0

In [81]:
dfr.loc[2, :] = dfr.apply(lambda x: x[0] + x[1] + 1, axis=0)
dfr

A    B    C    D
0  2.0  2.0  0.0  0.0
1  3.0  4.0  1.0  1.0
2  6.0  7.0  2.0  2.0
3  3.0  3.0  4.0  4.0

In [82]:
dfr.assign(E=lambda x: x["A"] + 1)
dfr

A    B    C    D    E
0  2.0  2.0  0.0  0.0  3.0
1  3.0  4.0  1.0  1.0  4.0
2  6.0  7.0  2.0  2.0  7.0
3  3.0  3.0  4.0  4.0  4.0

A    B    C    D
0  2.0  2.0  0.0  0.0
1  3.0  4.0  1.0  1.0
2  6.0  7.0  2.0  2.0
3  3.0  3.0  4.0  4.0

In [83]:
# select on the first dimension and then assign on the second dimension
# it will not succeed in assigning
dfr[[True, False, True, True]]["A"] = 3

/var/folders/hf/mw0wf2xn2ksbm7bc1d0hpln00000gn/T/ipykernel_26498/2810835239.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfr[[True, False, True, True]]["A"] = 3


In [84]:
dfr

A    B    C    D
0  2.0  2.0  0.0  0.0
1  3.0  4.0  1.0  1.0
2  6.0  7.0  2.0  2.0
3  3.0  3.0  4.0  4.0

In [85]:
dfr.loc[[True, False, True, True], "A"] = 3
dfr

A    B    C    D
0  3.0  2.0  0.0  0.0
1  3.0  4.0  1.0  1.0
2  3.0  7.0  2.0  2.0
3  3.0  3.0  4.0  4.0

In [86]:
dfc.set_index("B", inplace=True)

In [87]:
dfc

A    C         D
B                      
2.0  3.0  4.0  0.000000
4.0  3.0  4.0  1.000000
3.0  3.0  4.0  1.666667
3.0  3.0  4.0  4.000000

In [88]:
dfc.index = [0, 2, 1, 3]
dfc
dfr.drop("D", axis=1, inplace=True)
dfr

A    C         D
0  3.0  4.0  0.000000
2  3.0  4.0  1.000000
1  3.0  4.0  1.666667
3  3.0  4.0  4.000000

A    B    C
0  3.0  2.0  0.0
1  3.0  4.0  1.0
2  3.0  7.0  2.0
3  3.0  3.0  4.0

In [89]:
# concat two dataframes on row level, keep original index
pd.concat([dfc, dfr], axis=0, join="inner")

A    C
0  3.0  4.0
2  3.0  4.0
1  3.0  4.0
3  3.0  4.0
0  3.0  0.0
1  3.0  1.0
2  3.0  2.0
3  3.0  4.0

In [90]:
df = pd.DataFrame(
    {"A": [3, 5, 7, 6], "B": ["a", "b", "c", "d"]},
    index=pd.MultiIndex.from_product([["bar", "foo"], ["one", "two"]]),
)
df
sdf = df.stack()
sdf

A  B
bar one  3  a
    two  5  b
foo one  7  c
    two  6  d

bar  one  A    3
          B    a
     two  A    5
          B    b
foo  one  A    7
          B    c
     two  A    6
          B    d
dtype: object

In [91]:
sdf = pd.DataFrame(sdf)
sdf.index.names = ["first", "second", "third"]

sdf.rename(columns={0: "value"}, inplace=True)
sdf.columns = ["col"]
sdf = sdf.reset_index()
sdf

first second third col
0   bar    one     A   3
1   bar    one     B   a
2   bar    two     A   5
3   bar    two     B   b
4   foo    one     A   7
5   foo    one     B   c
6   foo    two     A   6
7   foo    two     B   d

In [92]:
df = pd.DataFrame(
    {
        "foo": ["one", "one", "one", "two", "two", "two"],
        "bar": ["A", "B", "C", "A", "B", "C"],
        "baz": [1, 2, 3, 4, 5, 6],
        "zoo": ["x", "y", "z", "q", "w", "t"],
    }
)
df

foo bar  baz zoo
0  one   A    1   x
1  one   B    2   y
2  one   C    3   z
3  two   A    4   q
4  two   B    5   w
5  two   C    6   t

In [93]:
df.pivot(index="foo", columns="baz", values="zoo")

baz    1    2    3    4    5    6
foo                              
one    x    y    z  NaN  NaN  NaN
two  NaN  NaN  NaN    q    w    t

In [94]:
# sort sub dataframe by baz, in result we see for each foo, baz is sorted
df.groupby("foo").apply(lambda x: x.sort_values("baz", ascending=False)).reset_index(
    drop=True
)

foo bar  baz zoo
0  one   C    3   z
1  one   B    2   y
2  one   A    1   x
3  two   C    6   t
4  two   B    5   w
5  two   A    4   q

In [95]:
def add_column(df, num):
    df["new"] = df["baz"] + num
    return df


df.index

RangeIndex(start=0, stop=6, step=1)

In [96]:
df = pd.read_csv("archive/sales.csv/sales.csv")
df

/var/folders/hf/mw0wf2xn2ksbm7bc1d0hpln00000gn/T/ipykernel_26498/4041522120.py:1: DtypeWarning: Columns (10,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("archive/sales.csv/sales.csv")


product_id store_id        date  sales  revenue  stock  price   
0             P0001    S0002  2017-01-02    0.0     0.00    8.0   6.25  \
1             P0001    S0012  2017-01-02    1.0     5.30    0.0   6.25   
2             P0001    S0013  2017-01-02    2.0    10.59    0.0   6.25   
3             P0001    S0023  2017-01-02    0.0     0.00    6.0   6.25   
4             P0001    S0025  2017-01-02    0.0     0.00    1.0   6.25   
...             ...      ...         ...    ...      ...    ...    ...   
19454833      P0748    S0125  2019-12-29    NaN      NaN    NaN  18.90   
19454834      P0748    S0126  2019-12-29    NaN      NaN    NaN  18.90   
19454835      P0748    S0131  2019-12-29    NaN      NaN    NaN  18.90   
19454836      P0748    S0132  2019-12-29    NaN      NaN    NaN  18.90   
19454837      P0748    S0142  2019-12-29    NaN      NaN    NaN  18.90   

         promo_type_1 promo_bin_1 promo_type_2 promo_bin_2  promo_discount_2   
0                PR14         NaN         PR03         NaN               NaN  \
1                PR14         NaN         PR03         NaN               NaN   
2                PR14         NaN         PR03         NaN               NaN   
3                PR14         NaN         PR03         NaN               NaN   
4                PR14         NaN         PR03         NaN               NaN   
...               ...         ...          ...         ...               ...   
19454833         PR14         NaN         PR03         NaN               NaN   
19454834         PR14         NaN         PR03         NaN               NaN   
19454835         PR14         NaN         PR03         NaN               NaN   
19454836         PR14         NaN         PR03         NaN               NaN   
19454837         PR14         NaN         PR03         NaN               NaN   

         promo_discount_type_2  
0                          NaN  
1                          NaN  
2                          NaN  
3                          NaN  
4                          NaN  
...                        ...  
19454833                   NaN  
19454834                   NaN  
19454835                   NaN  
19454836                   NaN  
19454837                   NaN  

[19454838 rows x 13 columns]

In [97]:
pd.PeriodIndex(df["date"][:1000], freq="Q")

PeriodIndex(['2017Q1', '2017Q1', '2017Q1', '2017Q1', '2017Q1', '2017Q1',
             '2017Q1', '2017Q1', '2017Q1', '2017Q1',
             ...
             '2017Q1', '2017Q1', '2017Q1', '2017Q1', '2017Q1', '2017Q1',
             '2017Q1', '2017Q1', '2017Q1', '2017Q1'],
            dtype='period[Q-DEC]', name='date', length=1000)

In [98]:
type(pd.to_datetime(df["date"][:1000], format="%Y-%m-%d", errors="coerce"))

pandas.core.series.Series

In [99]:
ts = pd.Series(np.random.randn(1000), index=pd.to_datetime(df["date"][:1000]))

In [100]:
ts.index

DatetimeIndex(['2017-01-02', '2017-01-02', '2017-01-02', '2017-01-02',
               '2017-01-02', '2017-01-02', '2017-01-02', '2017-01-02',
               '2017-01-02', '2017-01-02',
               ...
               '2017-01-02', '2017-01-02', '2017-01-02', '2017-01-02',
               '2017-01-02', '2017-01-02', '2017-01-02', '2017-01-02',
               '2017-01-02', '2017-01-02'],
              dtype='datetime64[ns]', name='date', length=1000, freq=None)

In [101]:
pd.interval_range(start=pd.Timestamp("2017-01-01"), periods=3, freq="MS")

IntervalIndex([(2017-01-01, 2017-02-01], (2017-02-01, 2017-03-01], (2017-03-01, 2017-04-01]], dtype='interval[datetime64[ns], right]')

In [102]:
df = pd.DataFrame({"A":[3,4],"B":[5,6]})
df

A  B
0  3  5
1  4  6

In [103]:
def add_ten(x):
    return x + 10

In [104]:
df.pipe(add_ten).pipe(add_ten)

A   B
0  23  25
1  24  26

In [105]:
def add(x, y, k):
    return x + y + k

df = pd.DataFrame({"A":[3,4],"B":[5,6]})
df.pipe(add, 4, k=6).pipe(add_ten)


A   B
0  23  25
1  24  26