In [2]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

# 创建一维数组
a = np.array([1, 2, 3, 4, 'abc'])
print(a)
print(a.dtype)

['1' '2' '3' '4' 'abc']
<U21


In [3]:
class A:
    pass

# 数组里的数据类型都是统一的
a = np.array([A(), 6])
print(a.dtype)
print(a)

object
[<__main__.A object at 0x111f148b0> 6]


In [4]:
np.arange(0, 5, 2) # 等价于 range(0, 5, 2)

array([0, 2, 4])

In [5]:
# 等差数据， [0, 1) 之间，10 个数据
np.linspace(0, 1, 10, endpoint=False)
# 等差数据， [0, 1] 之间，10 个数据
np.linspace(0, 1, 10, endpoint=True)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
# 二维数组
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
a
a.shape

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

(4, 3)

In [7]:
# 转换数组维度
a.reshape((3, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# 初始化数组
np.full((3, 3), fill_value=3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [11]:
# 转换一维数组成二维列向量，使用 -1 表示自动计算维度大小
a = np.array([1, 2, 3 ,4])
a = a.reshape((-1, 1))
a

array([[1],
       [2],
       [3],
       [4]])

In [13]:
# 数组访问
# 索引
a = [[1, 2, 3, 4], [1, 2, 3, 4]]
b = [[True, False, True, False], [False, True, True, False]]

In [14]:
# python 不支持这两种写法
a[1, 2]
a[b]

TypeError: list indices must be integers or slices, not tuple

In [15]:
# 布尔索引
a = np.array(a)
b = np.array(b)
a[b]

array([1, 3, 2, 3])

In [16]:
# 切片是引用，不是拷贝
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a[1:2, :]
b[0, 0] = -1
print(a)


[[ 1  2  3]
 [-1  5  6]]


In [17]:
# 数组存储
np.save('a.npy', a)

In [18]:
# 存储多个数组，使用字典的方式
np.savez('test.npz', a=a, b=b)

In [19]:
# 读取数组
data = np.load('test.npz')
data['a']
data.close()

array([[ 1,  2,  3],
       [-1,  5,  6]])

In [20]:
a = np.load('a.npy', mmap_mode='r+')
type(a)
# mmap_mode='r+' 表示以读写模式打开
# 在内存中修改，会直接修改文件
a[0, 1] = 1000

numpy.memmap

In [21]:
np.load('a.npy')

array([[   1, 1000,    3],
       [  -1,    5,    6]])