In [9]:
#!pip install git+https://github.com/d2l-ai/d2l-zh@release

  Cloning https://github.com/d2l-ai/d2l-zh (to revision release) to /private/var/folders/zg/1pb8nfp5473d_0jl7b7d8jyw0000gn/T/pip-req-build-qpfhhrq_
  Running command git clone --filter=blob:none --quiet https://github.com/d2l-ai/d2l-zh /private/var/folders/zg/1pb8nfp5473d_0jl7b7d8jyw0000gn/T/pip-req-build-qpfhhrq_
  on a case-insensitive filesystem) and only one from the same
  colliding group is in the working tree:

    'img/Marginal.svg'
    'img/marginal.svg'
    'img/Neuron.svg'
    'img/neuron.svg'
  Running command git checkout -b release --track origin/release
  Switched to a new branch 'release'
  branch 'release' set up to track 'origin/release'.
  Resolved https://github.com/d2l-ai/d2l-zh to commit 843d3d41dca48d8df65f4b324dd171d8bfe9c067
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
  Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 4.9 MB/s eta 0:00:00

In [4]:
import torch

In [5]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.size()

torch.Size([12])

In [7]:
torch.Size([12])

torch.Size([12])

In [8]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros((2,4))
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
y = torch.tensor([[2,3,4],[4,5,6]])
y

tensor([[2, 3, 4],
        [4, 5, 6]])

In [11]:
y.size()

torch.Size([2, 3])

In [19]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4)) 
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])

Z = torch.cat((X,Y),dim=0)
U = torch.cat((X,Y),dim=1)
print(Z,"\n")
print(U)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]) 

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [23]:
# 逻辑判断
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [24]:
# 求和
X.sum()

tensor(66.)

In [25]:
# 广播机制

a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)

a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [40]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [47]:
X[-1,:1]

tensor([8.])

In [48]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [53]:
# 写值
X[1,2] = 12
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 12.,  7.],
        [ 8.,  9., 10., 11.]])

In [54]:
# 运行操作导致重新分配内存
id(X)

4977546944

In [56]:
X = Y+X
id(X)

4978609824

In [58]:
# 执行原地操作，不影响地址
Z = torch.zeros_like(Y)
id(Z)

4977571168

In [59]:
Z[:]=X+Y
id(Z)

4977571168

In [64]:
A = X.numpy()
A

array([[ 6.,  4., 14., 12.],
       [ 7., 11., 21., 19.],
       [20., 18., 16., 14.]], dtype=float32)

In [66]:
B = torch.tensor(A)
B

tensor([[ 6.,  4., 14., 12.],
        [ 7., 11., 21., 19.],
        [20., 18., 16., 14.]])

In [67]:
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [70]:
C = torch.tensor([3.5])
C.item()

3.5