In [1]:
import torch

In [5]:
# 第二范数 L2
v = torch.arange(12,dtype=torch.float32).reshape((3,4))

norm = torch.linalg.norm(v)
norm

tensor(22.4944)

In [69]:
# Frobenius范数（也称为欧几里得范数）是针对矩阵的
# L2范数通常针对向量

# frobenius 范数
Z = torch.norm(torch.ones((4,9)))
Z

tensor(6.)

In [27]:
# 标量
x = torch.tensor([3.0])
y= torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [30]:
# 向量
x = torch.arange(4)
x[0]

tensor(0)

In [31]:
len(x)

4

In [33]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [35]:
# 转置
A.T

tensor([[ 0.,  4.,  8., 12., 16.],
        [ 1.,  5.,  9., 13., 17.],
        [ 2.,  6., 10., 14., 18.],
        [ 3.,  7., 11., 15., 19.]])

In [36]:
# 复制clone(), -- 深拷贝
B = A.clone()

In [37]:
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [38]:
# hadamard product -- 两个矩阵按元素乘法

A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [41]:
# 广播机制

a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)

a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [56]:
b

tensor([[0, 1]])

In [57]:
a.sum(axis=1,keepdim=True)  + b.sum(axis=1,keepdim=True) 

tensor([[1],
        [2],
        [3]])

In [60]:
a.sum(axis=0,keepdim=True)  + b.sum(axis=0,keepdim=True) 

tensor([[3, 4]])

In [46]:
a.sum(axis=1,keepdim=True) + b.sum(axis=1,keepdim=True) 

tensor([[1],
        [2],
        [3]])

In [65]:
A = torch.arange(20, dtype=torch.float32).reshape((5,4))
B = torch.tensor([2,3,6,8],dtype=torch.float32)

A.size()

torch.Size([5, 4])

In [66]:
B.size()

torch.Size([4])

In [67]:
torch.mv(A,B)

tensor([ 39., 115., 191., 267., 343.])

In [71]:

B.size()

torch.Size([4])

In [72]:
a = torch.arange(12).reshape(3,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [78]:
a.sum(axis=1,keepdim=True)

tensor([[ 6],
        [22],
        [38]])